### ISSUE TITLE
Error in migrations - missing timeline

### ISSUE THREAD

**Issue by raphaelrpl** [brazil-data-cube/bdc-catalog#92]
```bash
SQLALCHEMY_DATABASE_URI="postgresql://localhost:5434/catalog2" bdc-db alembic revision upgrade
/home/user/bdc-catalog/venv/lib/python3.7/site-packages/alembic/script/revision.py:154: UserWarning: Revision 149deb59082a referenced from 149deb59082a -> f3f27ad116d2 (head), timeline is not present
  % (downrev, rev)
Traceback (most recent call last):
  File "/home/user/bdc-catalog/venv/bin/bdc-db", line 8, in <module>
    sys.exit(cli())
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/flask_alembic/cli/click.py", line 114, in revision
    base.revision(message, empty, branch, parent, splice, depend, label, path)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/flask_alembic/cli/base.py", line 97, in revision
    get_alembic().revision(message, empty, branch, parent, splice, depend, label, path)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/flask_alembic/extension.py", line 391, in revision
    branch_exists = any(r for r in self.script_directory.revision_map.get_revisions(branch) if r is not None)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/alembic/script/revision.py", line 321, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/alembic/script/revision.py", line 501, in _resolve_revision_number
    self._revision_map
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/alembic/util/langhelpers.py", line 230, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/user/bdc-catalog/venv/lib/python3.7/site-packages/alembic/script/revision.py", line 156, in _revision_map
    down_revision = map_[downrev]
KeyError: '149deb59082a'
```

**Comment by raphaelrpl** [comment]
Resolved in cd1b85e4cf323691cf9f7dd538e87d8ed0796887
